### Obtener todos los tipos de cambio
GET http://localhost:3000/Tipodecambio

### Obtener tipo de cambio por fecha y codTipo
GET http://localhost:3000/Tipodecambio/by?fecha=02/07/2025&codTipo=V
### Crear un nuevo tipo de cambio
POST http://localhost:3000/Tipodecambio
Content-Type: application/json

{
  "fecPublica": "12/08/2024",
  "valTipo": "3.75",
  "codTipo": "C"
}

### Actualizar un tipo de cambio
PATCH http://localhost:3000/Tipodecambio/2024/08/12/C
Content-Type: application/json

{
  "valTipo": "3.80"
}

### Eliminar un tipo de cambio
DELETE http://localhost:3000/Tipodecambio?fecha=2024-08-12&codTipo=C